sudo: false
addons:
  apt:
    packages:
    - ed
    - vim-gtk
language: ruby
cache: bundler
rvm:
  - 1.9.3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rspec --format=documentation
